LabControl/Controllers/AlunoController.cs
using LabControl.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabControl.Controllers
{
    public class AlunoController : Controller
    {
        // POST: Aluno
        
        public ActionResult Index()
        {
            Comandos aluno = new Comandos();
            
            return View(aluno.listarAluno());
        }
        [HttpGet]
        public ActionResult Inserir()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Inserir(AlunoViewModel aluno)
        {
           

            if (!ModelState.IsValid)
                return View(aluno);

            Comandos cm = new Comandos();

            cm.cadastrarAluno(aluno.Ra, aluno.Nome, aluno.Email);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int ra)
        {
            Comandos c = new Comandos();
            AlunoViewModel aluno = c.listarAlunoRA(ra);
            return View(aluno);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirma(int ra)
        {
            Comandos cm = new Comandos();

            cm.deletarAluno(ra);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit (int ra)
        {
            Comandos c = new Comandos();
            AlunoViewModel aluno = c.listarAlunoRA(ra);
            return View(aluno);
        }
        [HttpGet]
        public ActionResult Details(int ra)
        {
            Comandos c = new Comandos();
            AlunoViewModel aluno = c.listarAlunoRA(ra);
            return View(aluno);
        }

        [HttpPost, ActionName("Edit")]
        public ActionResult EditConfirma(AlunoViewModel aluno)
        {


            Comandos cm = new Comandos();
            cm.editarAluno(aluno.Ra, aluno.Nome, aluno.Email);
            return RedirectToAction("Index");
        }
    }
}

LabControl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle de Labs</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de Labs", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Alunos", "Index", "Aluno")</li>
                </ul>
                <ul class="nav navbar-nav" align ="right">
                    <li>@Html.ActionLink(" " + Session["nomeUsuario"], "Contact", "Home")</li>
                </ul>
</div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle de Labs</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>